const chat=document.getElementById("chat");let selectedDate="all",selectedYear="all",selectedKind="all",query="";
const fmtDate=d=>new Date(d+"T00:00:00").toLocaleDateString("ko-KR",{year:"numeric",month:"long",day:"numeric",weekday:"short"});
const years=[...new Set(BUBBLE_DATA.messages.map(m=>m.date.slice(0,4)))].sort((a,b)=>b-a),dates=[...new Set(BUBBLE_DATA.messages.map(m=>m.date))].sort((a,b)=>b.localeCompare(a));
document.getElementById("artist").textContent=BUBBLE_DATA.artist;document.getElementById("count").textContent=BUBBLE_DATA.bubbleCount;
function filtered(){return BUBBLE_DATA.messages.filter(m=>(selectedDate==="all"||m.date===selectedDate)&&(selectedYear==="all"||m.date.startsWith(selectedYear))&&(selectedKind==="all"||m.type===selectedKind)&&(!query||((m.text||"")+" "+(m.title||"")+" "+(m.options||[]).join(" ")).toLowerCase().includes(query.toLowerCase())))}
function render(){chat.innerHTML="";let arr=filtered().sort((a,b)=>(a.date+(a.time||"")).localeCompare(b.date+(b.time||""))),last="";arr.forEach(m=>{if(m.date!==last){let d=document.createElement("div");d.className="date-divider";d.textContent=fmtDate(m.date);chat.appendChild(d);last=m.date}let row=document.createElement("section");row.className="msg";let p=document.createElement("img");p.className="profile";p.src=BUBBLE_DATA.profile;row.appendChild(p);let body=document.createElement("div");body.className="msg-body";let n=document.createElement("div");n.className="name";n.textContent="Evan hansen";body.appendChild(n);
if(m.type==="image"){let im=document.createElement("img");im.className="media";im.src=m.src;body.appendChild(im)}
else if(m.type==="audio"){let a=document.createElement("video");a.controls=true;a.playsInline=true;a.preload="metadata";a.src=m.src;a.className="audio-video";a.setAttribute("aria-label","음성 메시지 재생");body.appendChild(a);if(m.duration){let dur=document.createElement("small");dur.className="audio-duration";dur.textContent=m.duration;body.appendChild(dur)}if(m.transcript){let tr=document.createElement("div");tr.className="transcript";tr.textContent=m.transcript;body.appendChild(tr)}}
else if(m.type==="poll"){let b=document.createElement("div");b.className="bubble poll";let q=document.createElement("strong");q.textContent="📊 "+(m.text||"투표");b.appendChild(q);let choices=document.createElement("div");choices.className="poll-choices";(m.options||[]).forEach((o,i)=>{let c=document.createElement("div");c.className="poll-option";c.textContent=(i+1)+". "+o;choices.appendChild(c)});b.appendChild(choices);body.appendChild(b)}
else{let b=document.createElement("div");b.className="bubble"+(m.type==="reply"?" reply":"");if(m.type==="reply"){let st=document.createElement("strong");st.textContent=m.title;b.appendChild(st);let tx=document.createElement("div");tx.className="muted";tx.textContent=m.text;b.appendChild(tx)}else b.textContent=m.text;body.appendChild(b)}
if(m.time){let t=document.createElement("div");t.className="time";t.textContent=m.time;body.appendChild(t)}row.appendChild(body);chat.appendChild(row)});if(!arr.length){let e=document.createElement("div");e.style.textAlign="center";e.style.padding="60px 10px";e.style.color="#999";e.textContent="백업된 메시지가 없습니다.";chat.appendChild(e)}document.getElementById("dateLabel").textContent=selectedDate==="all"?"전체 기간":fmtDate(selectedDate)}
function panel(id,show=true){document.getElementById(id).classList.toggle("hidden",!show)}
document.getElementById("dateBtn").onclick=()=>panel("datePanel");document.getElementById("yearBtn").onclick=()=>panel("yearPanel");document.getElementById("filterBtn").onclick=()=>panel("filterPanel");document.getElementById("searchBtn").onclick=()=>{panel("searchPanel");document.getElementById("searchInput").focus()};document.getElementById("clearSearch").onclick=()=>{document.getElementById("searchInput").value="";query="";render();panel("searchPanel",false)};document.getElementById("searchInput").oninput=e=>{query=e.target.value.trim();render()};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>panel(b.dataset.close,false));
document.getElementById("dateChoices").innerHTML=dates.map(d=>`<button class="choice" data-date="${d}">${fmtDate(d)}</button>`).join("");document.getElementById("yearChoices").innerHTML=years.map(y=>`<div class="year-item"><button data-year="${y}">${y}년 <span class="match-count">${BUBBLE_DATA.messages.filter(m=>m.date.startsWith(y)).length}개</span></button></div>`).join("");
document.addEventListener("click",e=>{if(e.target.dataset.date!==undefined){selectedDate=e.target.dataset.date;selectedYear="all";panel("datePanel",false);render()}if(e.target.dataset.year){selectedYear=e.target.dataset.year;selectedDate="all";panel("yearPanel",false);render()}if(e.target.dataset.kind){selectedKind=e.target.dataset.kind;panel("filterPanel",false);render()}});document.getElementById("back").onclick=()=>history.back();render();